id: P006749
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 12:20:51.937982
source_metadata:
  id: bdr:W1PD159442
  title: བློ་གསལ་གཞོན་ནུའི་མགུལ་རྒྱན།
  author: ''
  volumes:
    3316411fd3124d61a4453eb7b6feb0dd:
      image_group_id: I2PD19031
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
