id: I63445F0A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T09:04:00+00:00'
last_modified: '2022-06-08T06:35:12.142143+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159442
  title: བློ་གསལ་གཞོན་ནུའི་མགུལ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '4248':
      image_group_id: I2PD19031
      title: ''
      total_pages: 264
      order: 1
      base_file: 4248.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
